runtime: nodejs18
service: api-store
env: standard
instance_class: F1
handlers:
  - url: .*
    script: auto
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

env_variables:
  DB_NAME: almacen
  DB_USER: postgres
  DB_PASSWORD: 'techbeta17$'
  DB_HOST: database-1.c1wm4t4m06ko.us-east-1.rds.amazonaws.com
  DB_PORT: 5432
  NODE_ENV: production